apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
  namespace: test
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp-container
        image: prcdocker/java-web-docker:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: test
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 8080
    targetPort: 8080
    name: javawebapp
    nodePort: 30004
